// AUTO-GENERATED BY scripts/generateAssetMappings.js
const scoreToMidi: Record<string, number> = {
  "air_on_the_g_string.musicxml": require("../../assets/air_on_the_g_string/air_on_the_g_string.mid"),
  "allegretto.musicxml": require("../../assets/allegretto/allegretto.mid"),
  "allegro.musicxml": require("../../assets/allegro/allegro.mid"),
  "andantino.musicxml": require("../../assets/andantino/andantino.mid"),
  "bourree.musicxml": require("../../assets/bourree/bourree.mid"),
  "chorus.musicxml": require("../../assets/chorus/chorus.mid"),
  "come_little_children.musicxml": require("../../assets/come_little_children/come_little_children.mid"),
  "french_folk_song.musicxml": require("../../assets/french_folk_song/french_folk_song.mid"),
  "gavotte.musicxml": require("../../assets/gavotte/gavotte.mid"),
  "go_tell_aunt_rhody.xml": require("../../assets/go_tell_aunt_rhody/go_tell_aunt_rhody.mid"),
  "hunters_chorus.musicxml": require("../../assets/hunters_chorus/hunters_chorus.mid"),
  "long_long_ago.musicxml": require("../../assets/long_long_ago/long_long_ago.mid"),
  "march_in_g.musicxml": require("../../assets/march_in_g/march_in_g.mid"),
  "may_song.musicxml": require("../../assets/may_song/may_song.mid"),
  "may_time.musicxml": require("../../assets/may_time/may_time.mid"),
  "minuet_in_c.musicxml": require("../../assets/minuet_in_c/minuet_in_c.mid"),
  "minuet_no_1.musicxml": require("../../assets/minuet_no_1/minuet_no_1.mid"),
  "minuet_no_3.musicxml": require("../../assets/minuet_no_3/minuet_no_3.mid"),
  "musette.musicxml": require("../../assets/musette/musette.mid"),
  "ode_to_joy.musicxml": require("../../assets/ode_to_joy/ode_to_joy.mid"),
  "rigadoon.musicxml": require("../../assets/rigadoon/rigadoon.mid"),
  "schumann_melody.musicxml": require("../../assets/schumann_melody/schumann_melody.mid"),
  "songs_of_wind.musicxml": require("../../assets/songs_of_wind/songs_of_wind.mid"),
  "the_two_grenadiers.musicxml": require("../../assets/the_two_grenadiers/the_two_grenadiers.mid"),
  "theme.musicxml": require("../../assets/theme/theme.mid")
};

export default scoreToMidi;
