import { Platform } from "react-native";
import { Asset } from "expo-asset";

interface AssetMap {
  web: string;
  ios: any;
  android: any;
}

interface ScoreDataFiles {
  refAudio: AssetMap;
  csvData: AssetMap;
}

// AUTO-GENERATED BY scripts/generateAssetMappings.js
export const unifiedScoreMap: Record<string, ScoreDataFiles> = {
  "air_on_the_g_string": {
    refAudio: {
      web: "/air_on_the_g_string/aotgs_solo_ref.wav",
      ios: require("../../assets/air_on_the_g_string/aotgs_solo_ref.wav"),
      android: require("../../assets/air_on_the_g_string/aotgs_solo_ref.wav"),
    },
    csvData: {
      web: "/air_on_the_g_string/aotgs_solo_100bpm.csv",
      ios: require("../../assets/air_on_the_g_string/aotgs_solo_100bpm.csv"),
      android: require("../../assets/air_on_the_g_string/aotgs_solo_100bpm.csv"),
    },
  },

  "allegretto": {
    refAudio: {
      web: "/allegretto/allegretto.wav",
      ios: require("../../assets/allegretto/allegretto.wav"),
      android: require("../../assets/allegretto/allegretto.wav"),
    },
    csvData: {
      web: "/allegretto/allegretto.csv",
      ios: require("../../assets/allegretto/allegretto.csv"),
      android: require("../../assets/allegretto/allegretto.csv"),
    },
  },

  "allegro": {
    refAudio: {
      web: "/allegro/allegro.wav",
      ios: require("../../assets/allegro/allegro.wav"),
      android: require("../../assets/allegro/allegro.wav"),
    },
    csvData: {
      web: "/allegro/allegro.csv",
      ios: require("../../assets/allegro/allegro.csv"),
      android: require("../../assets/allegro/allegro.csv"),
    },
  },

  "andantino": {
    refAudio: {
      web: "/andantino/andantino.wav",
      ios: require("../../assets/andantino/andantino.wav"),
      android: require("../../assets/andantino/andantino.wav"),
    },
    csvData: {
      web: "/andantino/andantino.csv",
      ios: require("../../assets/andantino/andantino.csv"),
      android: require("../../assets/andantino/andantino.csv"),
    },
  },

  "bourree": {
    refAudio: {
      web: "/bourree/bourree.wav",
      ios: require("../../assets/bourree/bourree.wav"),
      android: require("../../assets/bourree/bourree.wav"),
    },
    csvData: {
      web: "/bourree/bourree.csv",
      ios: require("../../assets/bourree/bourree.csv"),
      android: require("../../assets/bourree/bourree.csv"),
    },
  },

  "chorus": {
    refAudio: {
      web: "/chorus/chorus.wav",
      ios: require("../../assets/chorus/chorus.wav"),
      android: require("../../assets/chorus/chorus.wav"),
    },
    csvData: {
      web: "/chorus/chorus.csv",
      ios: require("../../assets/chorus/chorus.csv"),
      android: require("../../assets/chorus/chorus.csv"),
    },
  },

  "come_little_children": {
    refAudio: {
      web: "/come_little_children/come_little_children.wav",
      ios: require("../../assets/come_little_children/come_little_children.wav"),
      android: require("../../assets/come_little_children/come_little_children.wav"),
    },
    csvData: {
      web: "/come_little_children/come_little_children.csv",
      ios: require("../../assets/come_little_children/come_little_children.csv"),
      android: require("../../assets/come_little_children/come_little_children.csv"),
    },
  },

  "french_folk_song": {
    refAudio: {
      web: "/french_folk_song/french_folk_song.wav",
      ios: require("../../assets/french_folk_song/french_folk_song.wav"),
      android: require("../../assets/french_folk_song/french_folk_song.wav"),
    },
    csvData: {
      web: "/french_folk_song/french_folk_song.csv",
      ios: require("../../assets/french_folk_song/french_folk_song.csv"),
      android: require("../../assets/french_folk_song/french_folk_song.csv"),
    },
  },

  "gavotte": {
    refAudio: {
      web: "/gavotte/gavotte.wav",
      ios: require("../../assets/gavotte/gavotte.wav"),
      android: require("../../assets/gavotte/gavotte.wav"),
    },
    csvData: {
      web: "/gavotte/gavotte.csv",
      ios: require("../../assets/gavotte/gavotte.csv"),
      android: require("../../assets/gavotte/gavotte.csv"),
    },
  },

  "go_tell_aunt_rhody": {
    refAudio: {
      web: "/go_tell_aunt_rhody/5_go_tell_aunt_rhody-Violoncello50_ref.wav",
      ios: require("../../assets/go_tell_aunt_rhody/5_go_tell_aunt_rhody-Violoncello50_ref.wav"),
      android: require("../../assets/go_tell_aunt_rhody/5_go_tell_aunt_rhody-Violoncello50_ref.wav"),
    },
    csvData: {
      web: "/go_tell_aunt_rhody/5_go_tell_aunt_rhody_50_performance.csv",
      ios: require("../../assets/go_tell_aunt_rhody/5_go_tell_aunt_rhody_50_performance.csv"),
      android: require("../../assets/go_tell_aunt_rhody/5_go_tell_aunt_rhody_50_performance.csv"),
    },
  },

  "hunters_chorus": {
    refAudio: {
      web: "/hunters_chorus/hunters_chorus.wav",
      ios: require("../../assets/hunters_chorus/hunters_chorus.wav"),
      android: require("../../assets/hunters_chorus/hunters_chorus.wav"),
    },
    csvData: {
      web: "/hunters_chorus/hunters_chorus.csv",
      ios: require("../../assets/hunters_chorus/hunters_chorus.csv"),
      android: require("../../assets/hunters_chorus/hunters_chorus.csv"),
    },
  },

  "long_long_ago": {
    refAudio: {
      web: "/long_long_ago/long_long_ago.wav",
      ios: require("../../assets/long_long_ago/long_long_ago.wav"),
      android: require("../../assets/long_long_ago/long_long_ago.wav"),
    },
    csvData: {
      web: "/long_long_ago/long_long_ago.csv",
      ios: require("../../assets/long_long_ago/long_long_ago.csv"),
      android: require("../../assets/long_long_ago/long_long_ago.csv"),
    },
  },

  "march_in_g": {
    refAudio: {
      web: "/march_in_g/march_in_g.wav",
      ios: require("../../assets/march_in_g/march_in_g.wav"),
      android: require("../../assets/march_in_g/march_in_g.wav"),
    },
    csvData: {
      web: "/march_in_g/march_in_g.csv",
      ios: require("../../assets/march_in_g/march_in_g.csv"),
      android: require("../../assets/march_in_g/march_in_g.csv"),
    },
  },

  "may_song": {
    refAudio: {
      web: "/may_song/may_song.wav",
      ios: require("../../assets/may_song/may_song.wav"),
      android: require("../../assets/may_song/may_song.wav"),
    },
    csvData: {
      web: "/may_song/may_song.csv",
      ios: require("../../assets/may_song/may_song.csv"),
      android: require("../../assets/may_song/may_song.csv"),
    },
  },

  "may_time": {
    refAudio: {
      web: "/may_time/may_time.wav",
      ios: require("../../assets/may_time/may_time.wav"),
      android: require("../../assets/may_time/may_time.wav"),
    },
    csvData: {
      web: "/may_time/may_time.csv",
      ios: require("../../assets/may_time/may_time.csv"),
      android: require("../../assets/may_time/may_time.csv"),
    },
  },

  "minuet_in_c": {
    refAudio: {
      web: "/minuet_in_c/minuet_in_c.wav",
      ios: require("../../assets/minuet_in_c/minuet_in_c.wav"),
      android: require("../../assets/minuet_in_c/minuet_in_c.wav"),
    },
    csvData: {
      web: "/minuet_in_c/minuet_in_c.csv",
      ios: require("../../assets/minuet_in_c/minuet_in_c.csv"),
      android: require("../../assets/minuet_in_c/minuet_in_c.csv"),
    },
  },

  "minuet_no_1": {
    refAudio: {
      web: "/minuet_no_1/minuet_no_1.wav",
      ios: require("../../assets/minuet_no_1/minuet_no_1.wav"),
      android: require("../../assets/minuet_no_1/minuet_no_1.wav"),
    },
    csvData: {
      web: "/minuet_no_1/minuet_no_1.csv",
      ios: require("../../assets/minuet_no_1/minuet_no_1.csv"),
      android: require("../../assets/minuet_no_1/minuet_no_1.csv"),
    },
  },

  "minuet_no_3": {
    refAudio: {
      web: "/minuet_no_3/minuet_no_3.wav",
      ios: require("../../assets/minuet_no_3/minuet_no_3.wav"),
      android: require("../../assets/minuet_no_3/minuet_no_3.wav"),
    },
    csvData: {
      web: "/minuet_no_3/minuet_no_3.csv",
      ios: require("../../assets/minuet_no_3/minuet_no_3.csv"),
      android: require("../../assets/minuet_no_3/minuet_no_3.csv"),
    },
  },

  "musette": {
    refAudio: {
      web: "/musette/musette.wav",
      ios: require("../../assets/musette/musette.wav"),
      android: require("../../assets/musette/musette.wav"),
    },
    csvData: {
      web: "/musette/musette.csv",
      ios: require("../../assets/musette/musette.csv"),
      android: require("../../assets/musette/musette.csv"),
    },
  },

  "ode_to_joy": {
    refAudio: {
      web: "/ode_to_joy/o2j_ref.wav",
      ios: require("../../assets/ode_to_joy/o2j_ref.wav"),
      android: require("../../assets/ode_to_joy/o2j_ref.wav"),
    },
    csvData: {
      web: "/ode_to_joy/ode_to_joy_300bpm_NEW.csv",
      ios: require("../../assets/ode_to_joy/ode_to_joy_300bpm_NEW.csv"),
      android: require("../../assets/ode_to_joy/ode_to_joy_300bpm_NEW.csv"),
    },
  },

  "rigadoon": {
    refAudio: {
      web: "/rigadoon/rigadoon.wav",
      ios: require("../../assets/rigadoon/rigadoon.wav"),
      android: require("../../assets/rigadoon/rigadoon.wav"),
    },
    csvData: {
      web: "/rigadoon/rigadoon.csv",
      ios: require("../../assets/rigadoon/rigadoon.csv"),
      android: require("../../assets/rigadoon/rigadoon.csv"),
    },
  },

  "schumann_melody": {
    refAudio: {
      web: "/schumann_melody/ref.wav",
      ios: require("../../assets/schumann_melody/ref.wav"),
      android: require("../../assets/schumann_melody/ref.wav"),
    },
    csvData: {
      web: "/schumann_melody/schumann_melody_4sec.csv",
      ios: require("../../assets/schumann_melody/schumann_melody_4sec.csv"),
      android: require("../../assets/schumann_melody/schumann_melody_4sec.csv"),
    },
  },

  "songs_of_wind": {
    refAudio: {
      web: "/songs_of_wind/songs_of_wind.wav",
      ios: require("../../assets/songs_of_wind/songs_of_wind.wav"),
      android: require("../../assets/songs_of_wind/songs_of_wind.wav"),
    },
    csvData: {
      web: "/songs_of_wind/songs_of_wind.csv",
      ios: require("../../assets/songs_of_wind/songs_of_wind.csv"),
      android: require("../../assets/songs_of_wind/songs_of_wind.csv"),
    },
  },

  "the_two_grenadiers": {
    refAudio: {
      web: "/the_two_grenadiers/the_two_grenadiers.wav",
      ios: require("../../assets/the_two_grenadiers/the_two_grenadiers.wav"),
      android: require("../../assets/the_two_grenadiers/the_two_grenadiers.wav"),
    },
    csvData: {
      web: "/the_two_grenadiers/the_two_grenadiers.csv",
      ios: require("../../assets/the_two_grenadiers/the_two_grenadiers.csv"),
      android: require("../../assets/the_two_grenadiers/the_two_grenadiers.csv"),
    },
  },

  "theme": {
    refAudio: {
      web: "/theme/theme.wav",
      ios: require("../../assets/theme/theme.wav"),
      android: require("../../assets/theme/theme.wav"),
    },
    csvData: {
      web: "/theme/theme.csv",
      ios: require("../../assets/theme/theme.csv"),
      android: require("../../assets/theme/theme.csv"),
    },
  },
};

const getPlatformAsset = (assets: AssetMap): string | any => {
  if (Platform.OS === "web") {
    return assets.web;
  }
  if (Platform.OS === "android") {
    return Asset.fromModule(assets.android).uri;
  }
  return Asset.fromModule(assets.ios).uri;
};

export const getScoreRefAudio = (scoreName: string): string | any => {
  const score = unifiedScoreMap[scoreName];
  if (!score) throw new Error(`Score not found: ${scoreName}`);
  return getPlatformAsset(score.refAudio);
};

export const getScoreCSVData = (scoreName: string): string | any => {
  const score = unifiedScoreMap[scoreName];
  if (!score) throw new Error(`Score not found: ${scoreName}`);
  return getPlatformAsset(score.csvData);
};

export default unifiedScoreMap;
